name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: workstation
    steps:
      - uses: actions/checkout@v4
      - uses: ageorgeh/pnpm-action-setup@fix/skip-install-if-existing
        with:
          cache: true
          run_install: true
      - name: prettier
        run: |
          npx prettier . --check
      - name: build
        run: |
          pnpm build

      # Disabled for now - lots of stuff in svelte files that ill deal with later
      # - name: eslint
      #   run: |
      #     # npx eslint .
  test:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: ageorgeh/pnpm-action-setup@fix/skip-install-if-existing
        with:
          cache: true
          run_install: true
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps && npx playwright install chrome
      - name: build
        run: |
          pnpm build
      - name: test
        run: |
          pnpm test:e2e
