name: publish

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  # https://docs.npmjs.com/trusted-publishers#managing-trusted-publisher-configurations
  id-token: write # for generating oidc tokens
  contents: write
  issues: write
  pull-requests: write
  packages: write

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: workstation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ageorgeh/pnpm-action-setup@fix/skip-install-if-existing
        with:
          cache: true
          run_install: true

      - name: lint
        run: npx prettier . --check

      - name: build
        run: pnpm build

      - name: testing
        run: |
          npm config get globalconfig
          npm config get userconfig
          sed -E 's/(_authToken=).+/\1***redacted***/' $(npm config get globalconfig) || true
          sed -E 's/(_authToken=).+/\1***redacted***/' $(npm config get userconfig) || true


          npm config list -l
          env | grep -E "NODE_AUTH_TOKEN|NPM_TOKEN|NPM_CONFIG_|NPMRC" -i || true
      # - name: semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release
